/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"


void
add_prog_1(char *host,int *a,int n)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a.a_val=a;
	add_1_arg.a.a_len=n;
	add_1_arg.n=n;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Result: %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a[10];
	if (argc > 10) {
		printf ("usage: %s server_host max 10 numbers\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int i=0;
	for(i=2;i<argc;i++)
		a[i-2]=atoi(argv[i]);
	printf("Array sent\n");
	for(i=0;i<argc-2;i++)
		printf("%d \t",a[i]);
	add_prog_1 (host,a,argc-2);
exit (0);
}
