/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Called sum of array\n");
	printf("%d\n",argp->n);
	result=0;
	int i=0;
	for(i=0;i<argp->n;i++)
		printf("%d \t",argp->a.a_val[i]);
	for(i=0;i<argp->n;i++)
		result+=argp->a.a_val[i];
	printf("Return value: %d\n",result);
	return &result;
}
