/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct prog {
	char *progname;
};
typedef struct prog prog;

#define NFS_PROG 0x23451111
#define NFS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RUN_PROG 1
extern  char ** run_prog_1(prog *, CLIENT *);
extern  char ** run_prog_1_svc(prog *, struct svc_req *);
extern int nfs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RUN_PROG 1
extern  char ** run_prog_1();
extern  char ** run_prog_1_svc();
extern int nfs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_prog (XDR *, prog*);

#else /* K&R C */
extern bool_t xdr_prog ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
