/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
nfs_prog_1(char *host, char *progname)
{
	CLIENT *clnt;
	char * *result_1;
	prog  run_prog_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NFS_PROG, NFS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	run_prog_1_arg.progname=progname;
	result_1 = run_prog_1(&run_prog_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("acemaster> %s\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc > 10) {
		printf ("usage: %s server_host command\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int i=0;
	char argtosend[255];
	strcpy(argtosend,argv[2]);
	for(i=3;i<argc;i++)
	{
		strcat(argtosend," ");
		strcat(argtosend,argv[i]);
	}
	nfs_prog_1 (host,argtosend);
exit (0);
}
