/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#define READ_MAX_SIZE 512

char **
run_prog_1_svc(prog *argp, struct svc_req *rqstp)
{
	FILE* fpipe;
	static char* readPipeInto;
	static char * result;
	printf("Command to exec: %s\n",argp->progname);
	char* prog=argp->progname;
	readPipeInto = (char*)malloc((READ_MAX_SIZE + 1)*sizeof(char));
 	memset(readPipeInto, 0, READ_MAX_SIZE + 1);
 	char* program1AndProgram2=(char*)malloc((strlen(prog)));
 	strcpy(program1AndProgram2, argp->progname);
	 if ( !(fpipe = (FILE*)popen(program1AndProgram2,"r")) )
	 { 
	   perror("Cant open pipe!");
	   exit(1);
	 }
 	fread((char *)readPipeInto, READ_MAX_SIZE, 1, fpipe); 
 	pclose(fpipe); 
 	free(program1AndProgram2);
 	//return output to the client
 	return (char **)&readPipeInto;
}
