/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_prog (XDR *xdrs, prog *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->progname, 255))
		 return FALSE;
	return TRUE;
}
